### ISSUE TITLE
ajv-errors fails validation

### ISSUE THREAD

**Issue by jsmolina** [mocks-server/main#248]
**Describe the bug**
```
Error loading ajv-errors dependency, validations won't be executed. Visit https://mocks-server.org/docs/how-to-fix-ajv-errors-installation for further info.: Unexpected token ':'
         SyntaxError: Unexpected token ':'
             at new Function (<anonymous>)
             at Ajv.compileSchema (/src/node_modules/@mocks-server/core/node_modules/ajv/dist/compile/index.js:90:30)...
```
This error is documented in https://www.mocks-server.org/docs/how-to-fix-ajv-errors-installation/ but none of the proposed solutions worked.

Only forcing both of these package versions fixed it:
```
        "ajv": "8.9.0",
        "ajv-errors": "3.0.0",
```
**To Reproduce**
Updating ajv to 8.9.10 and having "@mocks-server/main": "2.6.2"

**Expected behavior**
No errors happen on validation.

**Comment by javierbrea** [comment]
Hi @jsmolina, thanks for the information. I'm currently working in the next major version, in which the `ajv-errors` dependency will be replaced by `better-ajv-errors`, so this issue will be solved.
