### ISSUE TITLE
How could be possible to pass headers and query params to a mocked HTTP request

### ISSUE THREAD

**Issue by ng-plex** [mocks-server/main#282]
**Is your feature request related to a problem? Please describe.**
I would need to pass query params and headers to a mocked request, I tried to pass the params in the url but it is not possible because the mock-server failed.

**Describe the solution you'd like**
Would be great to have the possibility to pass them to the requests. I also have the same endpoint for two requests differentiated by HTTP query params `grant_type`

**Comment by ng-plex** [comment]
Thank you @javierbrea i tried using the `options: filter` like following to differentiate between the same path for different routes where you passes query params as following:

```
{
    id: "login",
    url: "/oauth/token",
    method: "POST",
    variants: [
      {
        id: "success",
        options: {
          filter: function (req, res) {
            return req.params.grant_type === "password"
          },
        },
        response: {
          status: 201,
          body: LoginSuccessResponse,
        },
      },
    ],
  },
  {
    id: "refreshToken",
    url: "/oauth/token",
    method: "POST",
    variants: [
      {
        id: "success",
        options: {
          filter: function (req, res) {
            return req.params.grant_type === "refresh_token"
          },
        },
        response: {
          status: 201,
          body: refreshTokenSuccessResponse,
        },
      },
    ],
  },
```

I tried also with the middlewares without success. It is possible using the same route differentiate using query params?

**Comment by ng-plex** [comment]
Just solved like following:

```
{
    id: "token",
    url: "/cams-auth/oauth/token",
    method: "POST",
    variants: [
      {
        id: "success",
        response: (req, res, next) => {
          req.query.grant_type === "password"
            ? res.status(201).send(LoginSuccessResponse)
            : res.status(201).send(refreshTokenSuccessResponse)
        },
      },
    ],
  },
  ```

But, one question, is not more feasible the `options:filter` for that?

**Comment by javierbrea** [comment]
Hi @ng-plex, for the moment the `filter` option is [only available for route variants using the `proxy` handler](https://www.mocks-server.org/docs/get-started-routes). But it is a good idea to add this feature also to the `default` route handler. I will add it to the backlog.

Thanks for the feedback 😃
