### ISSUE TITLE
How can I use babel without .babelrc with NextJS?

### ISSUE THREAD

**Issue by jmaicaaan** [mocks-server/main#297]
My stack is Next v12 and TypeScript; On v12, there is an SWC option that enables us to have a better performance in the app. To enable SWC, we have to remove the babel configuration to enable SWC. However, running the app without babel configuration is throwing out errors.

It is complaining that it cannot understand the es6 import statements.

How can I use babel without babelrc? Can we have some sort of babel configuration that is only available in the `mocks.config.js`?

**Comment by javierbrea** [comment]
Hi @jmaicaaan,
You can use the `babelRegisterOptions` property in the `mocks.config.js` file to change the Babel configuration file name, so it will be loaded only by the Mocks Server application. For example:

```js
module.exports = {
  options: {
    log: "debug",
  },
  babelRegister: true,
  babelRegisterOptions: {
    configFile: "./mocks.babel.config.js",
  },
};
```

If you prefer to define the whole Babel configuration in the `mocks.config.js` file I think that it is also possible. Using the mentioned property you can define any other [`@babel/register` option](https://babeljs.io/docs/en/options).

**Comment by jmaicaaan** [comment]
> Hi @jmaicaaan, You can use the `babelRegisterOptions` property in the `mocks.config.js` file to change the Babel configuration file name, so it will be loaded only by the Mocks Server application. For example:
> 
> ```js
> module.exports = {
>   options: {
>     log: "debug",
>   },
>   babelRegister: true,
>   babelRegisterOptions: {
>     configFile: "./mocks.babel.config.js",
>   },
> };
> ```
> 
> If you prefer to define the whole Babel configuration in the `mocks.config.js` file I think that it is also possible. Using the mentioned property you can define any other [`@babel/register` option](https://babeljs.io/docs/en/options).

Hello! Thank you for the quick reply!

I will try that one and let you know 🚀

**Comment by jmaicaaan** [comment]
@javierbrea it's now working! Thanks for the help 🚀
