### ISSUE TITLE
[Question] Pointing mocks-server to config file custom path

### ISSUE THREAD

**Issue by ffind** [mocks-server/main#400]
Can I point somehow mocks-server command to config file that is not in the root of a project?
Something like `mocks-server --config=config/some/path/mocks.config.js`

**Comment by javierbrea** [comment]
Hi @ffind ,
You can use the [`config.fileSearchPlaces` option](https://www.mocks-server.org/docs/configuration/options#core-options):

```sh
mocks-server --config.fileSearchPlaces=config/some/path/mocks.config.js
```

The configuration file is loaded using [cosmiconfig](https://github.com/davidtheclark/cosmiconfig#searchplaces) behind the scenes, so this option also supports an array of possible values:

```sh
mocks-server --config.fileSearchPlaces=config/some/path/mocks.config.js --config.fileSearchPlaces=config/some/path/.mocks.yaml
```

You could also set this option [using an environment variable](https://www.mocks-server.org/docs/configuration/how-to-change-settings#environment-variables):

```sh
MOCKS_CONFIG_FILE_SEARCH_PLACES='["config/some/path/mocks.config.js"]'
```

**Comment by ffind** [comment]
Thank you @javierbrea !
