### ISSUE TITLE
Has any one tested this on MacOS Ventura 13.1? I am unable to access the mock server

### ISSUE THREAD

**Issue by vikramatcoupa** [mocks-server/main#453]
**Describe the bug**
I have recently upgraded to MacOS Ventura 13.1. Prior to the upgrade, I was able to access the https version of mock server with out any hassle. After upgrade, I am having issues with it. Now, I am seeing `ERR_ADDRESS_INVALID` while trying to access the server via browser. 

I see that the server is up and running as usual on the terminal. I have regenerated the certs and used them but no use. 

**To Reproduce**
- Create certs as mentioned [here](https://www.mocks-server.org/docs/guides/https-protocol/#creating-a-self-signed-certificate) and start the server

**Expected behavior**
- Able to access the server from browser. 

**Logs**
Not available

** Operating system, Node.js an npm versions, or browser version (please complete the following information):**
 - OS:  MacOS ventura 13.1
 - Node.js: 15.3.0
 - npm: 7.0.4
 - Browser: Chrome 108

![image](https://user-images.githubusercontent.com/75301978/209952466-1d1177e1-0a2f-4379-8985-925879fcd487.png)

When I do a curl to the base route, it responds with `Connection refused`

```
curl: (7) Failed to connect to localhost port 3100 after 6 ms: Connection refused
```

Any help is much appreciated. Stuck on this for couple of days.

**Comment by javierbrea** [comment]
Hi @vikramatcoupa ,
I have tried to reproduce the issue in MacOS Ventura, and it works fine in version 13.0.1. Is the issue related only to accessing the server via browser? I mean, is the server responding if you use Postman or CURL to perform requests?

**Comment by vikramatcoupa** [comment]
Thank you @javierbrea for your response. I am not seeing this issue anymore. I do not remember now as what I was done back then to get it working.
