### ISSUE TITLE
Auto generate doesn't work

### ISSUE THREAD

**Issue by doox911** [mocks-server/main#459]
**OS: Windows 11 Pro.**

`mocks.config.js`
```js
module.exports = {
  plugins: {
    openapi: {
      collection: {
        id: 'all-routes',
        from: 'base',
      },
    },
  },
};
```
structure `mock` directory:

```
- documents
-- openapi.json
- openapi
-- definitions.js
- routes
- collections.js
```
`definitions.js`:

```js
module.exports = [
  {
    basePath: '/api', // basePath to add to the url of every created route
    document: { // OpenAPI document
      $ref: '../documents/openapi.json',
    },
  },
];
```
Run command: `yarn mocks-server`:
```
────────────────────────────────────────────────────────────
⚠️  ALERTS
────────────────────────────────────────────────────────────
‧ Warning: [mock:collections:selected] Option 'mock.collections.selected' was not defined. Selecting the first collection found
‧ Warning: [mock:collections:load:all-routes:from] Collection with invalid 'from' property detected, 'base' was not found

────────────────────────────────────────────────────────────
ℹ️  CURRENT SETTINGS
────────────────────────────────────────────────────────────
‧ Server listening at: http://localhost:3100
‧ Delay: 0
‧ Current collection: all-routes
‧ Collections: 1
‧ Routes: 0
‧ Route variants: 0
‧ Log level: info
‧ Watch enabled: true

────────────────────────────────────────────────────────────
↕️  ACTIONS
────────────────────────────────────────────────────────────
? Select action: (Use arrow keys)
> Select collection 
  Use route variant 
  Restore route variants 
  Change delay 
  Restart server 
  Change log level 
  Switch watch 
(Move up and down to reveal more choices)
```
**Where are the auto-generated routes and collections?**

**Comment by javierbrea** [comment]
Hello @doox911 , it seems that you don't have a "base" collection (note the second warning displayed when you start the server). So, the plugin is not able to create the collection and routes because this produces an error.

**Comment by doox911** [comment]
> Hello @doox911 , it seems that you don't have a "base" collection (note the second warning displayed when you start the server). So, the plugin is not able to create the collection and routes because this produces an error.
> 
> You can remove the `from` property in the plugin options, and the collection will contain only the routes created by the openapi definition, or you can provide a valid collection to extend from.

I tryed:

```
// For a detailed explanation regarding each configuration property, visit:
// https://www.mocks-server.org/docs/configuration/how-to-change-settings
// https://www.mocks-server.org/docs/configuration/options

module.exports = {
  plugins: {
    openapi: {
      collection: {
        id: 'all-routes',
      },
    },
  },
};
```

And:
```
// For a detailed explanation regarding each configuration property, visit:
// https://www.mocks-server.org/docs/configuration/how-to-change-settings
// https://www.mocks-server.org/docs/configuration/options

module.exports = {
  plugins: {
    openapi: {},
  },
};
```
And I get:
```
────────────────────────────────────────────────────────────
⚠️  ALERTS
────────────────────────────────────────────────────────────
‧ Warning: [mock:collections:selected] Option 'mock.collections.selected' was not defined. Selecting the first collection found

────────────────────────────────────────────────────────────
ℹ️  CURRENT SETTINGS
────────────────────────────────────────────────────────────
‧ Server listening at: http://localhost:3100
‧ Delay: 0
‧ Current collection: openapi
‧ Collections: 1
‧ Routes: 0
‧ Route variants: 0
‧ Log level: info
‧ Watch enabled: true

────────────────────────────────────────────────────────────
↕️  ACTIONS
────────────────────────────────────────────────────────────
? Select action: (Use arrow keys)
> Select collection 
  Use route variant 
  Restore route variants 
  Change delay 
  Restart server 
  Change log level 
  Switch watch 
(Move up and down to reveal more choices)
```

**Comment by javierbrea** [comment]
Now, according to the logs, you don't have an error related to the configuration of the plugin, but it seems that your openAPI definition is not generating any route.

You can disable the inquirerCli plugin and increase the log level to see why. But I recommend you to review the [documentation about how Mocks Server converts OpenAPI docs into routes](https://www.mocks-server.org/docs/integrations/openapi/#openapi-conversion), so you can check if your OpenAPI definitions are compatible with the plugin, or if you have to add some properties in order to allow the server to detect and generate routes.

**Comment by doox911** [comment]
> inquirerCli

![Screenshot_55](https://user-images.githubusercontent.com/35161922/222659438-6d71abb1-8001-45e9-9ab0-2f9828a80cde.png)

**Comment by javierbrea** [comment]
Hi again @doox911 , I'm sorry but, as you can read in the docs, routes are generated from a combination of the OpenAPI paths, the methods, the examples in the responses, some custom properties that can be defined, etc. So, please read the docs deeply and be more specific in your comments. If you find something that it is not working according to the docs, or if you don't understand an specific point, I'll be happy to help you.

**Comment by doox911** [comment]
> Hi again @doox911 , I'm sorry but, as you can read in the docs, routes are generated from a combination of the OpenAPI paths, the methods, the examples in the responses, some custom properties that can be defined, etc. So, please read the docs deeply and be more specific in your comments. If you find something that it is not working according to the docs, or if you don't understand an specific point, I'll be happy to help you.

I have read and the only difference is the lack of examples in the Openapi schema, right?. I really don't understand what is missing to create routes at least?

**Comment by doox911** [comment]
> Hi again @doox911 , I'm sorry but, as you can read in the docs, routes are generated from a combination of the OpenAPI paths, the methods, the examples in the responses, some custom properties that can be defined, etc. So, please read the docs deeply and be more specific in your comments. If you find something that it is not working according to the docs, or if you don't understand an specific point, I'll be happy to help you.

Hurray! It turns out that nothing is created without examples... Thank you for your help!

**Comment by javierbrea** [comment]
> > Hi again @doox911 , I'm sorry but, as you can read in the docs, routes are generated from a combination of the OpenAPI paths, the methods, the examples in the responses, some custom properties that can be defined, etc. So, please read the docs deeply and be more specific in your comments. If you find something that it is not working according to the docs, or if you don't understand an specific point, I'll be happy to help you.
> 
> Hurray! It turns out that nothing is created without examples... Thank you for your help!

Yes, that's right, examples are needed because it has no sense to create route variants for sending anything 😉 . I'm glad you found the problem.
