### ISSUE TITLE
OpenAPI: Variants are not generated for responses with a single `example` key

### ISSUE THREAD

**Issue by davidmhewitt** [mocks-server/main#472]
**Describe the bug**
The open API specification supports _either_ setting `examples`, or `example`, on the content for a response:
https://swagger.io/specification/#media-type-object

Currently, the plugin only looks for the `examples` key, and generates a variant for each of the example responses:
https://github.com/mocks-server/main/blob/bf9dd81d142e796efe90f523aec8b271f0a645e3/packages/plugin-openapi/src/openapi.ts#L115-L123

So, if we parse a valid OpenAPI description that _only_ has an `example` key, we get no variant generated for it, leading to no route being generated in a lot of cases.

**To Reproduce**
Parse an OpenAPI description that has a single `example` key for a response.

**Expected behavior**
A variant and route to be generated for either way of setting example responses.

**Comment by javierbrea** [comment]
Hi @davidmhewitt , you're right, thanks for reporting it! 😃

**Comment by davidmhewitt** [comment]
@javierbrea No problem, thanks for the quick response!

I opened PR #473 that resolves this for me. Let me know any feedback on it or if anything needs changing!

**Comment by javierbrea** [comment]
@davidmhewitt , thanks for the PR! I will add some tests to it and create a new release ASAP 😃

**Comment by javierbrea** [comment]
Released on [v4.1.0](https://github.com/mocks-server/main/releases/tag/v4.1.0).
